<a href="https://colab.research.google.com/github/04b811/ipynb/blob/main/26_03numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

a = np.array([12,34,26,18,10])
#cria uma matriz unidimensional
print(a)
print(a.dtype)

[12 34 26 18 10]
int64


In [3]:
import numpy as np

b = np.array([[7,2,23],[12,27,4],[5,34,23]])
#cria uma matriz bidimensional
print(b)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [5]:
import numpy as np

d = np.zeros([4,3])
# cria uma matriz 4x3 com valores 0
print(d)

f = np.eye(5)
# cria uma matriz quadrada com diagonal principal com quatro valores 0
print(f)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
import numpy as np
g = np.random.random((5))
print(g)

# valores aleatórios ^^

[0.28633215 0.33886311 0.05852781 0.66269844 0.34627002]


In [8]:
import numpy as np
k = np.array([[17,22,43], [27,25,14], [15,24,32]])
# cria a matriz bidmensional k
print(k)
# mostra a  matriz k
print(k[0][1])
# mostra um elemento específico da matriz k
print(k.shape)
# mostra o tamanho das dimensões da matriz k
print(k.max())
# mostra o maior valor da matriz k
print(k.min())
# mostra o menor valor da matriz k
print(k.sum())
# mostra a soma dos valores da matriz k
print(k.mean())
# mostra o valor da média dos valores da matriz k
print(k.std())
# mostra o desvio padrão da matriz (standard deviation
                                                                                                                             )

[[17 22 43]
 [27 25 14]
 [15 24 32]]
22
(3, 3)
43
14
219
24.333333333333332
8.615231988880057
